### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by krisives** [jasonpang/Interceptor#1]
I am using this wrapper and would like to credit whoever made it / include your license in my project - but I don't see what license it is. I would prefer a BSD or MIT license, which would be distributed with my binary and displayed in the about dialog.

My project: https://github.com/krisives/GRemote

Cheers & Thanks!

**Comment by krisives** [comment]
Bump

**Comment by jasonpang** [comment]
Hi Kristopher, so sorry for responding 2 weeks late. Apparently all
notifications from Github go to my spam folder automatically.

For the "interceptor.dll", that is made by Francisco Lopes. The homepage
for his project is here http://oblita.com/interception.html. His Github
(which has the repository for his Interception project) is
herehttps://github.com/oblitum
.

For my "Interceptor.dll" wrapper, you can use it however you would like.
You don't need to link back to me or give any credit (though if you want
that would be welcome). You can modify the source, redistribute it, do
whatever you want with it. Have fun!

**Comment by filippobottega** [comment]
Thank you! ;)

**Comment by jasonpang** [comment]
Actually I decided to add the MIT License, which hopefully shouldn't cause any issues. It's such a small library, I definitely don't care about anybody who used it in the last 3 years without license attribution. I just figured it would be a better license than releasing it into the public domain since I spent a small amount of time into it (and I've been using it since).

@filippobottega @krisives or whoever was using this before I added the license just now, please don't worry about the MIT License addition, and you can continue doing whatever you want with it.

Hope you're building some cool stuff!

**Comment by krisives** [comment]
MIT license is great thanks 🙏
